[package]
name = "lsr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = "2.33"
chrono = "0.4"
tabular = "0.1.4"
users = "0.11"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
pretty_assertions = "1.4.0"
rand = "0.8"
