[package]
name = "grepr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = "2.33"
regex = "1"
walkdir = "2"
sys-info = "0.9"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
pretty_assertions = "1.4.0"
rand = "0.8"
